services:
  sync:
    container_name: libretube-sync
    image: ghcr.io/libre-tube/sync-server:main-sqlite
    build:
      context: .
      args:
        - "DATABASE_BACKEND=sqlite"
    environment:
      - "DATABASE_URL=./db.sqlite"
      - "SECRET_KEY=changeme"
      - "REGISTRATION_ENABLED=true"
      - "VALIDATION_ENABLED=true" # validate all user provided data by checking it against YouTube's RSS feeds
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
