name: Create and publish a Docker image

on:
  push:
#     branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        database-backend: [postgres, sqlite]

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      sign: false # Reduces build times significantly
      cache: true
      cache-scope: ${{ github.repository }}-${{ matrix.database-backend }}
      cache-mode: max # Also cache build layers
      meta-images: ghcr.io/${{ github.repository }}
      meta-flavor: |
        suffix=-${{ matrix.database-backend }}
      build-args: |
        DATABASE_BACKEND=${{ matrix.database-backend }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
